languages:
  Ruby: true
  JavaScript: true
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  reek:
    enabled: true

Metrics/LineLength:
  Max: 100

ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
  exclude_paths:
  - config/**/*
  - db/**/*
  - script/**/*
  - spec/**/*
  - vendor/**/*
  - "Gemfile.lock"
