# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6205e7b5dc00f0497f24e26f5426f93eacfc587ef04bac2c63dec4b7cc532c702a6103e6562bc6bdb61b63fe1e9553632822073f77072499eb253ab4fcb81e78

test:
  secret_key_base: a8a70d421913984546d2251d9b8c7eba085472a4ede298cce01012e7a4ffc3a6c70561fb7d55fb48bc7824f236b1f11bb1bce6a9537176bb3a20cfcfef8416a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
